
#
#
# Copyright 2016 The Symphony Software Foundation
#
# Licensed to The Symphony Software Foundation (SSF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

language: java

install: true
script:
- "if [[ \"$TRAVIS_PULL_REQUEST\" = \"false\" && $TRAVIS_BRANCH =~ dev ]]; then mvn clean deploy -Pversioneye -DtransitiveDependencies=true --settings settings.xml -Dbuild.provisioning=false; fi"
- "if [[ \"$TRAVIS_PULL_REQUEST\" != \"false\" ]]; then mvn clean install ; fi"

jdk:
  - openjdk11

env:
  global:
   # The encrypted COVERITY_SCAN_TOKEN, created via the "travis encrypt" command using the project repo's public key
   - secure: "qSjSBty//s1mc4XnXej8RM8Oe1rYP6RSbQqvLoiJph2F8nQpYnh8wBhILyvnPEshFKsK4IDtUz+GDClUJN0WwYCI65zcwtggAIT9frIpjuoQVYrE2oNUFfwCzl2fxXrFKQuUZ/fInDTdRgyFSQlpDK0i1AcB1WzCAKnVtWEBqOa+vYWh22cJRaEGyYNS1fw14ib299fWihBTO0PYIfJBHFM5BB27YxdE6bmEzZj2Zb4n2p3n83LV6ZLYBlKXrMLAVonaU/jCBJzhjKNYkHZuWGRVcL0eemYyddcz+oqzLlCwIAgqfFMnl5xKn1bNs7dU2WQXhqQJDpcblB6LnsDBBWnFmQ7NGolLLfqPd4Tb7sTMVGDyjNivTBNNCef+Nh2SlzntEsGrLyWGyVK+jA2LSc1vA6oRk2ogecJo0kHEyFjF5ShOmSd4b1oHxtEdAQ+RSe5FKFyecnXcGZPcbxXm1pwqWC2MbQIVshWeak6Fnha3w6NWRFEk/gS9KMnjuODFCwrAmr/qAv2fkUAHyAdIEzYYqhSqk4zEG/IJr486KuVTRgpTjuLZS4WjabdIszxr83SCD3mnuma/46V89rXUORcNe/MAtiePGpZUPdmXX0y+D9G7F2UXp+IVZnPv7Yphafo3Fb8YgvRfcFzWqfOredtoPGubKEgOIlxlr1PLpsE="
   -  CODECLIMATE_REPO_TOKEN: ac494106e383000b4c9f4f7bbcf15ba040b44a6c4a9082b3184072dda2c021d5

notifications:
  email:
    recipients:
      - dev-notify@symphony.foundation

addons:
  coverity_scan:
    project:
      name: "symphonyoss/messageml-utils"
      description: "Build submitted via Travis CI"
    notification_email: dev-notify@symphony.foundation
    build_command_prepend: "mvn clean"
    build_command:   "mvn  -DskipTests=true compile"
    branch_pattern: $COVERITY_BRANCH_PATTERN
